on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm-community'
          java-version: '21'
          native-image-musl: true

      - uses: gradle/gradle-build-action@v3

      - name: build
        run: ./gradlew nativeCompile

      - name: publish docker
        run: |
          echo $TOKEN | docker login ghcr.io -u rotilho --password-stdin
          
          docker build -t ghcr.io/attocash/work-coordinator:${{ github.sha }} . --pull
          docker push ghcr.io/attocash/work-coordinator:${{ github.sha }}
          
          BRANCH_NAME=${{ github.ref_name }}
          BRANCH_NAME=${BRANCH_NAME//\//_}
          
          docker tag ghcr.io/attocash/work-coordinator:${{ github.sha }} ghcr.io/attocash/work-coordinator:$BRANCH_NAME
          docker push ghcr.io/attocash/work-coordinator:$BRANCH_NAME
        env:
          TOKEN: ${{ secrets.token }}